version: "3.8"

services:
  todo:
    build: .
    container_name: todo
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
